server {
    listen       8080;
    server_name  localhost;

    root   /usr/share/nginx/html;
    index  index.html;

    # SPA React
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy → Backend Despachos (IP inyectada como variable de entorno BACKEND_DESPACHOS)
    location /api/despachos/ {
        proxy_pass         http://${BACKEND_DESPACHOS}:8081/;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
    }

    # Proxy → Backend Ventas (IP inyectada como variable de entorno BACKEND_VENTAS)
    location /api/ventas/ {
        proxy_pass         http://${BACKEND_VENTAS}:8080/;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
    }

    access_log  /dev/stdout;
    error_log   /dev/stderr warn;
}
